"""Shared helpers for racenex event importers: slugify, Nominatim geocoding
(with disk cache), .env.local loading, Supabase REST apply, and SQL export.
Every importer in this directory writes rows shaped as:

    {slug, name, sport_type, discipline, distance_key, distance_label,
     event_date (date), city, country_code, lat, lng}

targeting the same `events` table, so this logic only needs to live once.
"""

import json
import re
import sys
import time
import unicodedata
import urllib.parse
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent.parent
CACHE_FILE = HERE / ".geocode_cache.json"

CONTACT_EMAIL = "mathieu@roestermundt.de"
USER_AGENT = f"racenex-importer/0.1 (+https://github.com/mathieuroe/racenex; {CONTACT_EMAIL})"


def slugify(text: str) -> str:
    normalized = unicodedata.normalize("NFKD", text)
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii")
    ascii_text = ascii_text.lower()
    ascii_text = re.sub(r"[^a-z0-9]+", "-", ascii_text)
    return ascii_text.strip("-")


def load_geocode_cache() -> dict:
    if CACHE_FILE.exists():
        return json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    return {}


def save_geocode_cache(cache: dict) -> None:
    CACHE_FILE.write_text(json.dumps(cache, indent=2, ensure_ascii=False), encoding="utf-8")


def geocode(city: str, country_code: str, cache: dict) -> tuple[float, float] | None:
    key = f"{city}|{country_code}"
    if key in cache:
        return tuple(cache[key]) if cache[key] else None

    params = urllib.parse.urlencode(
        {"q": f"{city}, {country_code}", "format": "jsonv2", "limit": 1}
    )
    url = f"https://nominatim.openstreetmap.org/search?{params}"
    req = urllib.request.Request(
        url,
        headers={"User-Agent": USER_AGENT, "Accept-Language": "en"},
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as exc:  # noqa: BLE001 - best-effort geocoding
        print(f"  ! geocode failed for {city}, {country_code}: {exc}", file=sys.stderr)
        cache[key] = None
        time.sleep(1)
        return None

    if not data:
        cache[key] = None
        time.sleep(1)
        return None

    lat, lng = float(data[0]["lat"]), float(data[0]["lon"])
    cache[key] = [lat, lng]
    time.sleep(1)  # Nominatim usage policy: max 1 request/second
    return lat, lng


def geocode_rows(rows: list[dict]) -> None:
    """Geocode every unique (city, country_code) in rows in place, using the
    shared disk cache so repeat cities across importer runs cost 0 requests."""
    cache = load_geocode_cache()
    unique_places = sorted({(r["city"], r["country_code"]) for r in rows if r["city"]})
    print(f"Geocoding {len(unique_places)} unique places via Nominatim (1 req/sec)...")
    for city, country_code in unique_places:
        geocode(city, country_code, cache)
    save_geocode_cache(cache)
    for r in rows:
        if r["city"]:
            coords = cache.get(f"{r['city']}|{r['country_code']}")
            r["lat"], r["lng"] = tuple(coords) if coords else (None, None)
        else:
            r["lat"], r["lng"] = None, None


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def build_insert_sql(rows: list[dict], source_comment: str) -> str:
    lines = [
        f"-- Generated by {source_comment} — REVIEW BEFORE RUNNING.",
        "-- Only event-level metadata: name, date, place, sport, distance.",
        "-- No results or participant data included by design.",
        "",
        "insert into events",
        "  (slug, name, sport_type, discipline, distance_key, distance_label,",
        "   event_date, city, country_code, lat, lng, is_activated)",
        "values",
    ]
    value_rows = []
    for r in rows:
        lat = "null" if r["lat"] is None else repr(r["lat"])
        lng = "null" if r["lng"] is None else repr(r["lng"])
        city = "null" if not r["city"] else f"'{sql_escape(r['city'])}'"
        discipline = "null" if not r.get("discipline") else f"'{r['discipline']}'"
        distance_key = "null" if not r.get("distance_key") else f"'{r['distance_key']}'"
        distance_label = "null" if not r.get("distance_label") else f"'{sql_escape(r['distance_label'])}'"
        value_rows.append(
            "  ('{slug}', '{name}', '{sport_type}', {discipline}, {distance_key}, "
            "{distance_label}, '{event_date}', {city}, '{country_code}', {lat}, {lng}, false)".format(
                slug=sql_escape(r["slug"]),
                name=sql_escape(r["name"]),
                sport_type=r["sport_type"],
                discipline=discipline,
                distance_key=distance_key,
                distance_label=distance_label,
                event_date=r["event_date"].isoformat(),
                city=city,
                country_code=r["country_code"],
                lat=lat,
                lng=lng,
            )
        )
    lines.append(",\n".join(value_rows))
    lines.append("on conflict (slug) do nothing;")
    return "\n".join(lines) + "\n"


def load_env_local() -> dict:
    env_path = PROJECT_ROOT / ".env.local"
    env: dict[str, str] = {}
    if not env_path.exists():
        return env
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        value = value.strip()
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        env[key.strip()] = value
    return env


def apply_to_supabase(rows: list[dict]) -> None:
    """Insert rows directly via the Supabase REST API (PostgREST), using the
    service-role key so RLS doesn't block it. Duplicate slugs are ignored
    server-side (on_conflict=slug + resolution=ignore-duplicates), same
    semantics as the SQL file's ON CONFLICT (slug) DO NOTHING.
    """
    env = load_env_local()
    base_url = env.get("NEXT_PUBLIC_SUPABASE_URL")
    service_key = env.get("SUPABASE_SECRET_KEY") or env.get("SUPABASE_SERVICE_ROLE_KEY")
    if not base_url or not service_key:
        raise RuntimeError(
            "NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SECRET_KEY not found in .env.local — "
            "run `vercel env pull .env.local` first."
        )

    payload = [
        {
            "slug": r["slug"],
            "name": r["name"],
            "sport_type": r["sport_type"],
            "discipline": r.get("discipline"),
            "distance_key": r.get("distance_key"),
            "distance_label": r.get("distance_label"),
            "event_date": r["event_date"].isoformat(),
            "city": r["city"],
            "country_code": r["country_code"],
            "lat": r["lat"],
            "lng": r["lng"],
            "is_activated": False,
        }
        for r in rows
    ]

    url = f"{base_url}/rest/v1/events?on_conflict=slug"
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        method="POST",
        headers={
            "apikey": service_key,
            "Authorization": f"Bearer {service_key}",
            "Content-Type": "application/json",
            "Prefer": "resolution=ignore-duplicates,return=representation",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        result = json.loads(resp.read().decode("utf-8"))
    print(f"Applied to Supabase: {len(result)} of {len(rows)} rows inserted (rest were duplicate slugs).")
