#!/usr/bin/env python3
"""
racenex event_stats importer — DUV Ultra Marathon Statistics (pilot)

Source: https://statistik.d-u-v.org/ (Deutsche Ultramarathon-Vereinigung
e.V.). Checked before building this: no robots.txt on the site (no
restriction found), no explicit terms-of-use prohibition on reuse
found. DUV's own privacy page states their data "stammen aus
öffentlich zugänglichen Quellen (Zweitverwertung)" — they already do
the same kind of secondary-use aggregation this script does. Contrast
with MikaTiming (the results host for e.g. the Berlin Marathon), whose
robots.txt is a blanket `Disallow: /` — deliberately not touched here.

This is Ebene 1 of the schema (event_stats — anonymous aggregates,
DSGVO-unkritisch by design). It fetches ONE past race's full results
page, computes aggregate statistics in memory, and DISCARDS every
individual result immediately after aggregating: no runner name, no
individual time, no nationality, no birth year is ever written
anywhere. Only the aggregate (finisher_count, avg/median/best time,
a finish-time histogram, per-category median) becomes an event_stats
row. Do not extend this script to persist per-runner data.

Usage:
    python3 event_stats_importer.py \
        --duv-event 119993 --racenex-event <events.id> --year 2025 [--apply]

Output:
    db/imports/event_stats_<duv-event>.sql — INSERT statement for
    manual review. With --apply, also inserted directly via the
    Supabase REST API.
"""

import argparse
import re
import statistics
from datetime import date
from pathlib import Path

from common import USER_AGENT, load_env_local
import json
import urllib.request

HERE = Path(__file__).resolve().parent
OUTPUT_DIR = HERE.parent / "imports"

ROW_PAT = re.compile(r"<tr class='(?:odd|even)'>(.*?)</tr>", re.S)
CELL_PAT = re.compile(r"<td[^>]*>(.*?)</td>", re.S)
TAG_PAT = re.compile(r"<[^>]+>")


def clean(cell: str) -> str:
    return TAG_PAT.sub("", cell).replace("&nbsp;", " ").strip()


def parse_time_to_sec(text: str) -> int | None:
    text = text.replace("h", "").strip()
    parts = text.split(":")
    if len(parts) != 3:
        return None
    try:
        h, m, s = (int(p) for p in parts)
    except ValueError:
        return None
    return h * 3600 + m * 60 + s


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", errors="ignore")


def compute_stats(html_doc: str) -> dict:
    """Parses the results table and returns only aggregate numbers —
    the per-row data (name, country, birth year, ...) never leaves this
    function."""
    times: list[int] = []
    by_category: dict[str, list[int]] = {}

    for row_html in ROW_PAT.findall(html_doc):
        cells = [clean(c) for c in CELL_PAT.findall(row_html)]
        if len(cells) < 9:
            continue
        sec = parse_time_to_sec(cells[1])
        if sec is None:
            continue
        category = cells[8] or "unknown"
        times.append(sec)
        by_category.setdefault(category, []).append(sec)

    if not times:
        raise RuntimeError("No parseable results found on that page.")

    times.sort()
    bucket_sec = 1800  # 30-minute buckets
    lo = (times[0] // bucket_sec) * bucket_sec
    hi = ((times[-1] // bucket_sec) + 1) * bucket_sec
    distribution = []
    for start in range(lo, hi, bucket_sec):
        end = start + bucket_sec
        count = sum(1 for t in times if start <= t < end)
        if count:
            distribution.append({"from_sec": start, "to_sec": end, "count": count})

    ag_distribution = [
        {"ag": ag, "count": len(secs), "median_sec": int(statistics.median(secs))}
        for ag, secs in sorted(by_category.items())
    ]

    return {
        "finisher_count": len(times),
        "avg_finish_sec": int(statistics.mean(times)),
        "median_finish_sec": int(statistics.median(times)),
        "best_finish_sec": times[0],
        "distribution": distribution,
        "ag_distribution": ag_distribution,
    }


def build_sql(racenex_event_id: str, year: int, stats: dict, source_note: str) -> str:
    return (
        "-- Generated by db/importers/event_stats_importer.py — REVIEW BEFORE RUNNING.\n"
        "-- Aggregate numbers only. No individual results included.\n\n"
        "insert into event_stats\n"
        "  (event_id, year, finisher_count, avg_finish_sec, median_finish_sec,\n"
        "   best_finish_sec, distribution, ag_distribution, source_note)\n"
        "values\n"
        "  ('{event_id}', {year}, {finisher_count}, {avg}, {median}, {best},\n"
        "   '{distribution}'::jsonb, '{ag_distribution}'::jsonb, '{source_note}')\n"
        "on conflict (event_id, year) do update set\n"
        "  finisher_count = excluded.finisher_count,\n"
        "  avg_finish_sec = excluded.avg_finish_sec,\n"
        "  median_finish_sec = excluded.median_finish_sec,\n"
        "  best_finish_sec = excluded.best_finish_sec,\n"
        "  distribution = excluded.distribution,\n"
        "  ag_distribution = excluded.ag_distribution,\n"
        "  source_note = excluded.source_note;\n"
    ).format(
        event_id=racenex_event_id,
        year=year,
        finisher_count=stats["finisher_count"],
        avg=stats["avg_finish_sec"],
        median=stats["median_finish_sec"],
        best=stats["best_finish_sec"],
        distribution=json.dumps(stats["distribution"]).replace("'", "''"),
        ag_distribution=json.dumps(stats["ag_distribution"]).replace("'", "''"),
        source_note=source_note.replace("'", "''"),
    )


def apply_to_supabase(racenex_event_id: str, year: int, stats: dict, source_note: str) -> None:
    env = load_env_local()
    base_url = env.get("NEXT_PUBLIC_SUPABASE_URL")
    service_key = env.get("SUPABASE_SECRET_KEY") or env.get("SUPABASE_SERVICE_ROLE_KEY")
    if not base_url or not service_key:
        raise RuntimeError("NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SECRET_KEY not found in .env.local")

    payload = {
        "event_id": racenex_event_id,
        "year": year,
        "finisher_count": stats["finisher_count"],
        "avg_finish_sec": stats["avg_finish_sec"],
        "median_finish_sec": stats["median_finish_sec"],
        "best_finish_sec": stats["best_finish_sec"],
        "distribution": stats["distribution"],
        "ag_distribution": stats["ag_distribution"],
        "source_note": source_note,
    }
    url = f"{base_url}/rest/v1/event_stats?on_conflict=event_id,year"
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        method="POST",
        headers={
            "apikey": service_key,
            "Authorization": f"Bearer {service_key}",
            "Content-Type": "application/json",
            "Prefer": "resolution=merge-duplicates,return=representation",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        result = json.loads(resp.read().decode("utf-8"))
    print(f"Applied to Supabase: {len(result)} row(s) upserted.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--duv-event", required=True, help="DUV event id (from getresultevent.php?event=...)")
    parser.add_argument("--racenex-event", required=True, help="racenex events.id (uuid) this stat row belongs to")
    parser.add_argument("--year", type=int, required=True, help="year of the race edition being aggregated")
    parser.add_argument("--apply", action="store_true", help="also insert directly into Supabase")
    args = parser.parse_args()

    url = f"https://statistik.d-u-v.org/getresultevent.php?event={args.duv_event}"
    print(f"Fetching {url} ...")
    html_doc = fetch(url)

    print("Aggregating (individual results are discarded immediately after)...")
    stats = compute_stats(html_doc)
    print(
        f"{stats['finisher_count']} finishers — "
        f"best {stats['best_finish_sec']}s, median {stats['median_finish_sec']}s, avg {stats['avg_finish_sec']}s"
    )

    source_note = f"DUV statistik.d-u-v.org, event {args.duv_event}, aggregated {date.today().isoformat()}"
    sql = build_sql(args.racenex_event, args.year, stats, source_note)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUTPUT_DIR / f"event_stats_{args.duv_event}.sql"
    out_path.write_text(sql, encoding="utf-8")

    if args.apply:
        print(f"Wrote {out_path}. Applying to Supabase now...")
        apply_to_supabase(args.racenex_event, args.year, stats, source_note)
    else:
        print(f"Wrote {out_path}. Nothing was executed against any database.")


if __name__ == "__main__":
    main()
